#ifndef FILES_H
#define FILES_H 1

/* auto generated by genfs.py */

#include "fs/status.json"
#include "fs/index.html"
#include "fs/loadsweep.json"
#include "fs/loadsweep.csv"
#include "fs/index.html.big"


#endif
