#!/usr/bin/env python
import glob,os


filedefs = "/* auto generated by genfs.py */\n\n"
filesh = "#ifndef FILES_H\n#define FILES_H 1\n\n"+filedefs

os.chdir("files");

for f in glob.glob("*"):
    print f
    os.system("xxd -i '"+f+"' '../fs/"+f+"'")
    sum = ord('/')
    for l in f:
        sum += ord(l)
    filedefs += "#define TEST_%s %d\n"%(f.upper().replace('.','_'),sum)
    filesh += '#include "fs/'+f+'"'
filesh += "\n\n#endif\n"

open("../filedefs.h","w").write(filedefs)
open("../files.h","w").write(filesh)


